version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./laravel-app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - mysql-db

  nginx-server:
    container_name: nginx-server
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=text-analyzer
      - MYSQL_USER=test
      - MYSQL_PASSWORD=pass!234
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local    